baseURL = "http://0.0.0.0:1313"
title = "HB Hisam"

copyright = "Â© 2025 [Hisam Fahri](https://hisam.dev). Built with [Hugo Book](https://github.com/alex-shpak/hugo-book/)."

disablePathToLower = true
enableGitInfo = true

[module]
[[module.imports]]
path = "github.com/alex-shpak/hugo-book"

[params]
  BookTheme = "auto"
  BookToC = true
  BookSection = "*"
  BookRepo = "https://github.com/hisamafahri/template-hugo-book/"
  BookLastChangeLink = "{{ .Site.Params.BookRepo }}/commit/{{ .GitInfo.Hash }}"
  BookEditLink = "{{ .Site.Params.BookRepo }}/edit/main/{{ .Path }}"
  BookPortableLinks = "warning"
  BookTranslatedOnly = false